/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import clases.Conexiones;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINEDUCYT
 */
public class MasDetalles extends javax.swing.JFrame {

    int ID = 0;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form MasDetalles
     */
    public MasDetalles() {
        initComponents();

        this.setLocationRelativeTo(null);
        setTitle("Mas informacion del producto");

        ImageIcon wallpaper = new ImageIcon("src/articulos/" + ID + ".png");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelFoto.getWidth(),
                LabelFoto.getHeight(), Image.SCALE_DEFAULT));

        ImageIcon wallpaper1 = new ImageIcon("src/images/wallpaper.png");
        Icon icon1 = new ImageIcon(wallpaper1.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icon1);
        LabelFoto.setIcon(icon);

        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        Table.setShowGrid(false);
        Table = new JTable(model);
        jScrollPane2.setViewportView(Table);

        model.addColumn("ID");
        model.addColumn("Nombre");

        try {
            Connection cn2 = Conexiones.conexion();
            PreparedStatement pst2 = cn2.prepareStatement("SELECT MAX(ID) FROM articulos");
            ResultSet rs2 = pst2.executeQuery();

            if (rs2.next()) {
                ID = rs2.getInt("MAX(ID)");
            }

        } catch (Exception e) {
            System.out.print("Error al buscar el ID" + e);
        }

    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource(
                "images/iconoapp.png"));
        return retValue;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LabelFoto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 120, 60));

        LabelFoto.setBackground(new java.awt.Color(255, 255, 255));
        LabelFoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 150, 120));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setOpaque(false);
        Table.setSelectionBackground(new java.awt.Color(0, 255, 204));
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 11, 240, 280));

        jTextField1.setBackground(new java.awt.Color(0, 153, 153));
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 190, 40));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Añadir Foto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, 70));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Nombre = jTextField1.getText().trim();
        Connection cnz = Conexiones.conexion();
        try {
            cnz = Conexiones.conexion();
            PreparedStatement pstz = cnz.prepareStatement(
                    "insert into pronombres values(?,?,?)");

            pstz.setString(1, "0");
            pstz.setString(2, Nombre);
            pstz.setInt(3, ID);

            pstz.executeUpdate();
            cnz.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        JOptionPane.showMessageDialog(null, "Añadido Exitosamente");

        try {
            cnz = Conexiones.conexion();
            PreparedStatement pst = cnz.prepareStatement(
                    "select ID, Nombre from pronombres where IdProducto = '" + ID + "'");
            ResultSet rs = pst.executeQuery();

            for (int i = 0; i < Table.getRowCount(); i++) {
                model.removeRow(i);
                i--;
            }

            while (rs.next()) {
                Object[] fila = new Object[2];

                for (int i = 0; i < 2; i++) {

                    fila[i] = rs.getObject(i + 1);

                }
                model.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println("Error al llenar la tabla de pronombres: " + e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JOptionPane.showMessageDialog(null, "Objeto añadido exitosamente "
                + "\n\n\n presione actualizar para que aparesca el articulo");
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        JFileChooser jf = new JFileChooser();
        jf.setMultiSelectionEnabled(false);

        if (jf.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            //estas lineas de codigo son para copiar el archivo
            rsdragdropfiles.RSDragDropFiles.setCopiar(jf.getSelectedFile().toString(),
                    "src/articulos/" + ID + ".png");

        }

        ImageIcon wallpaper = new ImageIcon("src/articulos/" + ID + ".png");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelFoto.getWidth(),
                LabelFoto.getHeight(), Image.SCALE_DEFAULT));

        LabelFoto.setIcon(icon);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasDetalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasDetalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasDetalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasDetalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasDetalles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTable Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
