/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import clases.Conexiones;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MINEDUCYT
 */
public class NuevoProducto extends javax.swing.JFrame {

    int ID;

    /**
     * Creates new form NuevoProducto
     */
    public NuevoProducto() {
        initComponents();

        this.setLocationRelativeTo(null);
        setTitle("Añadir Producto");
        setResizable(false);

        ImageIcon wallpaper = new ImageIcon("src/images/Wallpaper3.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icon);

        ImageIcon marca = new ImageIcon("src/marcas/Inexistente.png");
        Icon icono = new ImageIcon(marca.getImage().getScaledInstance(LabelMArca.getWidth(),
                LabelMArca.getHeight(), Image.SCALE_DEFAULT));
        LabelMArca.setIcon(icono);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource(
                "images/iconoapp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        TxtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        CmbMarca = new javax.swing.JComboBox<>();
        LabelMArca = new javax.swing.JLabel();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtDescripcion.setBackground(new java.awt.Color(0, 153, 153));
        TxtDescripcion.setColumns(20);
        TxtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        TxtDescripcion.setRows(5);
        TxtDescripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(TxtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 290, 250));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripción:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        TxtPrecio.setBackground(new java.awt.Color(0, 153, 153));
        TxtPrecio.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        TxtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        TxtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrecio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 220, 40));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        TxtNombre.setBackground(new java.awt.Color(0, 153, 153));
        TxtNombre.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        TxtNombre.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 220, 40));

        name.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Nombre:");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mas Detalles");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 220, 40));

        CmbMarca.setBackground(new java.awt.Color(0, 153, 153));
        CmbMarca.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        CmbMarca.setForeground(new java.awt.Color(255, 255, 255));
        CmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Truper", "Viduc", "Total", "Iml", "Inversiones Asiaticas", "Nulo" }));
        CmbMarca.setSelectedIndex(5);
        CmbMarca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CmbMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbMarcaItemStateChanged(evt);
            }
        });
        getContentPane().add(CmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 220, 40));

        LabelMArca.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabelMArca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 150));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int Marca;
        String Precio, Name, sMarca = "", Descripcion;
        Precio = TxtPrecio.getText().trim();
        Descripcion = TxtDescripcion.getText().trim();
        Name = TxtNombre.getText().trim();
        Marca = CmbMarca.getSelectedIndex();

        if (Marca == 0) {
            sMarca = "Truper";
        } else if (Marca == 1) {
            sMarca = "Viduc";
        } else if (Marca == 2) {
            sMarca = "Total";
        } else if (Marca == 3) {
            sMarca = "Iml";
        } else if (Marca == 4) {
            sMarca = "Inversiones Asiaticas";
        } else if (Marca == 5) {
            sMarca = "Nulo";
        }

        if (!Precio.equals("") && !Name.equals("") && !sMarca.equals("") && !Descripcion.equals("")) {

            try {

                Connection cnz = Conexiones.conexion();
                PreparedStatement pstz = cnz.prepareStatement(
                        "insert into articulos values(?,?,?,?,?,?)");

                pstz.setString(1, "0");
                pstz.setString(2, Name);
                pstz.setString(3, Precio);
                pstz.setString(4, Descripcion);
                pstz.setString(5, "Si Tenemos");
                pstz.setString(6, sMarca);
                
                pstz.executeUpdate();
                cnz.close();
            } catch (Exception e) {
                System.out.println("Error al Llenar los datos: " + e);
            }
               new MasDetalles().setVisible(true);
               this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CmbMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbMarcaItemStateChanged

        int Marca = CmbMarca.getSelectedIndex();

        ImageIcon marca = new ImageIcon("");
        LabelMArca.setOpaque(false);

        if (Marca == 0) {

            marca = new ImageIcon("src/marcas/Truper.png");
            LabelMArca.setOpaque(true);

        } else if (Marca == 1) {

            marca = new ImageIcon("src/marcas/Viduc.png");
            LabelMArca.setOpaque(true);

        } else if (Marca == 2) {

            marca = new ImageIcon("src/marcas/Total.png");
            LabelMArca.setOpaque(true);

        } else if (Marca == 3) {

            marca = new ImageIcon("src/marcas/Iml.png");
            LabelMArca.setOpaque(true);

        } else if (Marca == 4) {

            marca = new ImageIcon("src/marcas/Inversiones Asiaticas.png");
            LabelMArca.setOpaque(true);

        } else if (Marca == 5) {

            marca = new ImageIcon("src/marcas/Inexistente.png");
            LabelMArca.setOpaque(false);

        }

        Icon icon = new ImageIcon(marca.getImage().getScaledInstance(LabelMArca.getWidth(),
                LabelMArca.getHeight(), Image.SCALE_DEFAULT));
        LabelMArca.setIcon(icon);


    }//GEN-LAST:event_CmbMarcaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbMarca;
    private javax.swing.JLabel LabelMArca;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextArea TxtDescripcion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
